---
name: continuous_integration

on:
  push:
    branches:
      - development
  pull_request:
    branches:
      - development

jobs:
  test_suite:
    runs-on: ubuntu-latest
    env:
      NPM_CONFIG_USER: root
      CYPRESS_ADMIN_USER_PASSWORD: ${{ secrets.CYPRESS_ADMIN_USER_PASSWORD }}
      CYPRESS_AUTH_URL: ${{ secrets.CYPRESS_AUTH_URL }}
      CYPRESS_AUTH0_CLIENT_ID: ${{ secrets.CYPRESS_AUTH0_CLIENT_ID }}
      CYPRESS_AUTH0_CLIENT_SECRET: ${{ secrets.CYPRESS_AUTH0_CLIENT_SECRET }}
      CYPRESS_PORTAL_USER_PASSWORD: ${{ secrets.CYPRESS_PORTAL_USER_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ secrets.GPR_USERNAME }}
          password: ${{ secrets.GPR_PERSONAL_ACCESS_TOKEN }}
      - name: Start Docker Compose
        run: docker-compose up -d
        env:
          AUTH0_CLIENT_ID: ${{ secrets.AUTH0_CLIENT_ID }}
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}
          SENDGRID_API_KEY: ${{ secrets.SENDGRID_API_KEY }}
          AUTH0_TENANT: neon-law-testing.auth0.com
          COMPOSE_HTTP_TIMEOUT: 300
      - name: Install depedencies
        run: |
          docker exec shell yarn install --frozen-lockfile
          sudo chown -R $USER .
          yarn install --frozen-lockfile
      - name: Lint Markdown files.
        run: docker exec shell yarn markdown-lint
      - name: Lint JavaScript files.
        run: docker exec shell yarn lint
      - name: Type-check TypeScript Files.
        run: docker exec shell yarn check-types
      - name: Run Jest tests and publish coverage to Code Climate.
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{secrets.CC_TEST_REPORTER_ID}}
        with:
          coverageCommand: docker exec shell yarn test
      - name: Run Cypress tests for @neonlaw/interface
        uses: cypress-io/github-action@v2
        with:
          record: true
          wait-on-timeout: 300
          wait-on: 'http://127.0.0.1:8000'
          working-directory: ./packages/interface
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GPR_PERSONAL_ACCESS_TOKEN }}
      - name: Run PGRita checks
        uses: pgrita/action@main
        env:
          PGRITA_TOKEN: ${{ secrets.PGRITA_TOKEN }}
          DATABASE_URL: postgres://postgres:password@127.0.0.1:5432/postgres
        with:
          project: neonlaw/codebase
      - name: Check api.tsx file against development server
        run: |
          docker exec shell yarn graphql-codegen
          git diff -G. --exit-code ./packages/shared-ui/src/utils/api.tsx
